---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cernopendata-config
data:
  cernopendata.cfg: |-
    
    # Database
    SQLALCHEMY_DATABASE_URI='postgresql+psycopg2://cernopendata:dbpass123@cod-db:5432/cernopendata'
    
    # Redis
    CACHE_REDIS_HOST='cod-cache'
    CACHE_REDIS_URL='redis://cod-cache:6379/0'
    ACCOUNTS_SESSION_REDIS_URL='redis://cod-cache:6379/1'
    
    # Celery
    BROKER_URL='amqp://guest:guest@cod-mq:5672/'
    CELERY_RESULT_BACKEND='redis://cod-cache:6379/2'
    
    # Elasticsearch
    SEARCH_ELASTIC_HOSTS='cod-search'
