---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cds-cache
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cds-cache
    spec:
      volumes:
      - name: cache
        persistentVolumeClaim:
          claimName: cache
      containers:
      - name: cds-cache
        image: redis
        ports:
        - containerPort: 5432
          name: tcp
        volumeMounts:
        - name: cache
          mountPath: /data
