---
apiVersion: v1
kind: DeploymentConfig
metadata:
  name: cod-cache
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cod-cache
    spec:
      containers:
      - name: cod-cache
        image: redis
        ports:
        - containerPort: 5432
          name: tcp
