---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cds-cache
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cds-cache
    spec:
      containers:
      - name: cds-cache
        image: redis
        ports:
        - containerPort: 5432
          name: tcp
#        volumeMounts:
#          name: data
#          mountPath: /data
#      volumes:
#        - name: data
#          persistentVolumeClaim:
#            claimName: cache
