---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cds-db
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cds-db
    spec:
      containers:
      - name: cds-db
        image: centos/postgresql-95-centos7
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRESQL_USER
          value: cds
        - name: POSTGRESQL_DATABASE
          value: cds
        - name: POSTGRESQL_PASSWORD
          value: dbpass123
#        volumeMounts:
#          name: data
#          mountPath: /var/lib/pgsql/data
#      volumes:
#        - name: data
#          persistentVolumeClaim:
#            claimName: db
