---
apiVersion: v1
kind: DeploymentConfig
metadata:
  name: cod-db
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cod-db
    spec:
      containers:
      - name: cod-db
        image: centos/postgresql-95-centos7
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRESQL_USER
          value: cernopendata
        - name: POSTGRESQL_DATABASE
          value: cernopendata
        - name: POSTGRESQL_PASSWORD
          value: dbpass123
#        volumeMounts:
#          name: data
#          mountPath: /var/lib/pgsql/data
#      volumes:
#        - name: data
#          persistentVolumeClaim:
#            claimName: db
