---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cds-mq
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cds-mq
    spec:
      containers:
      - name: cds-mq
        image: rabbitmq
        ports:
        - containerPort: 4369
        - containerPort: 5672
