---
apiVersion: v1
kind: DeploymentConfig
metadata:
  name: cod-proxy
spec:
  replicas: 1
  template:
    metadata:
      name: cod-proxy
      labels:
        app: cod-proxy
    spec:
      containers:
      - name: cod-proxy
        image: cod-nginx
        ports:
        - containerPort: 8080
          protocol: TCP
        volumeMounts:
          - name: nginx-config
            mountPath: /etc/nginx/conf.d
          - name: var-run
            mountPath: /var/run
          - name: var-cache-nginx
            mountPath: /var/cache/nginx
          - name: var-log-nginx
            mountPath: /var/log/nginx
          - name: static
            mountPath: /static
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config
        - name: var-run
          emptyDir: {}
        - name: var-cache-nginx
          emptyDir: {}
        - name: var-log-nginx
          emptyDir: {}
        - name: static
          emptyDir: {}
  triggers:
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - cod-proxy
        from:
          kind: ImageStreamTag
          name: cod-nginx:latest
    - type: ConfigChange
