---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cds-search
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cds-search
    spec:
      containers:
      - name: cds-search
        image: switowski/cds-search
        ports:
        - containerPort: 9200
        - containerPort: 9300
#        volumeMounts:
#          - mountPath: /usr/share/elasticsearch/data/elasticsearch
#            name: data
#      volumes:
#        - name: data
#          persistentVolumeClaim:
#            claimName: search
