---
apiVersion: v1
kind: DeploymentConfig
metadata:
  name: cod-search
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cod-search
    spec:
      containers:
      - name: cod-search
        image: diegodelemos/cod-search
        ports:
        - containerPort: 9200
        - containerPort: 9300

# This DeploymentConfig needs to provide a volume mounted under
# `/usr/share/elasticsearch/data/elasticsearch`
