---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cds-web
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cds-web
    spec:
      containers:
      - name: cds-web
        image: switowski/cds-web:0.0.5
        # command:
        #   - '/bin/bash'
        #   - '-c'
        #   - |-
        #     cp /cds-config/* /usr/local/var/cds-instance/ &&
        #     exec cds run -h 0.0.0.0
        ports:
        - containerPort: 5000
          name: http
        volumeMounts:
          - name: configuration
            mountPath: /cds-config
          - name: logs
            mountPath: /logs
        env:
        - name: VIRTUALENVWRAPPER_PYTHON
          value: /usr/local/bin/python
        - name: APP_SQLALCHEMY_DATABASE_URI
          value: postgresql+psycopg2://cds:dbpass123@cds-db:5432/cds
        - name: APP_CACHE_REDIS_HOST
          value: cds-cache
        - name: APP_CACHE_REDIS_URL
          value: redis://cds-cache:6379/0
        - name: APP_ACCOUNTS_SESSION_REDIS_URL
          value: redis://cds-cache:6379/1
        - name: APP_BROKER_URL
          value: amqp://guest:guest@cds-mq:5672/
        - name: APP_CELERY_RESULT_BACKEND
          value: redis://cds-cache:6379/2
        - name: APP_SEARCH_ELASTIC_HOSTS
          value: cds-search
      volumes:
        - name: configuration
          configMap:
            name: cds-config
        - name: logs
          emptyDir: {}
