---
apiVersion: v1
kind: DeploymentConfig
metadata:
  name: cod-web
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cod-web
    spec:
      containers:
      - name: cod-web
        image: web
        command:
          - '/bin/bash'
          - '-c'
          - |-
            cp /cod-config/* /usr/local/var/cernopendata-instance/ &&
            exec cernopendata run -h 0.0.0.0
        ports:
        - containerPort: 5000
          name: http
        volumeMounts:
          - name: configuration
            mountPath: /cod-config
        env:
        - name: VIRTUALENVWRAPPER_PYTHON
          value: /usr/local/bin/python
        - name: APP_SQLALCHEMY_DATABASE_URI
          value: postgresql+psycopg2://cernopendata:dbpass123@cod-db:5432/cernopendata
        - name: APP_CACHE_REDIS_HOST
          value: cod-cache
        - name: APP_CACHE_REDIS_URL
          value: redis://cod-cache:6379/0
        - name: APP_ACCOUNTS_SESSION_REDIS_URL
          value: redis://cod-cache:6379/1
        # Celery 3
        - name: APP_BROKER_URL
          value: amqp://guest:guest@cod-mq:5672/
        # Celery 4
        - name: APP_CELERY_BROKER_URL
          value: amqp://guest:guest@cod-mq:5672/
        - name: APP_CELERY_RESULT_BACKEND
          value: redis://cod-cache:6379/2
        - name: APP_SEARCH_ELASTIC_HOSTS
          value: cod-search
      volumes:
        - name: configuration
          configMap:
            name: cernopendata-config
  triggers:
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - cod-web
        from:
          kind: ImageStreamTag
          name: web:latest
    - type: ConfigChange
