---
apiVersion: v1
kind: Service
metadata:
  name: cod-mq
  labels:
    run: cod-mq
spec:
  ports:
  - name: tcp
    port: 4369
    protocol: TCP
  - name: management
    port: 5672
    protocol: TCP
  selector:
    app: cod-mq
