---
apiVersion: v1
kind: Service
metadata:
  name: cds-mq
  labels:
    run: cds-mq
spec:
  ports:
    - name: tcp
      port: 4369
      protocol: TCP
    - name: management
      port: 5672
      protocol: TCP
  selector:
    app: cds-mq
